# SPDX-FileCopyrightText: 2026 kumihan contributors
#
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "jlreq-spacing"
description = "Mojikumi: inter-character spacing between JLReq character classes"
keywords = ["japanese", "typesetting", "mojikumi", "text-layout", "no-std"]
categories = ["text-processing", "internationalization", "no-std::no-alloc"]
readme = "../../README.md"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
jlreq-class = { path = "../jlreq-class", version = "0.0.0" }
jlreq-spec = { path = "../jlreq-spec", version = "0.0.0" }
jlreq-unit = { path = "../jlreq-unit", version = "0.0.0" }

[lints]
workspace = true
