#!/bin/sh
# SPDX-FileCopyrightText: 2026 jlreq contributors
#
# SPDX-License-Identifier: MIT OR Apache-2.0

set -eu

if [ "$#" -ne 5 ]; then
    echo "usage: census-all.sh CENSUS RUST OCAML RACKET COMMITTED-SUMMARY" >&2
    exit 2
fi

probe=$1
rust_engine=$2
ocaml_engine=$3
racket_engine=$4
committed_summary=$5
output_dir=target/census
generated_summary=$output_dir/conformance-summary.md
rows=$output_dir/conformance-summary.rows

mkdir -p "$output_dir"
: > "$rows"

kinds=$("$probe" kinds)
kind_count=$(printf '%s\n' "$kinds" | sed '/^$/d' | wc -l | tr -d ' ')
if [ "$kind_count" -ne 10 ]; then
    echo "census registry has $kind_count kinds; release protocol v1 requires exactly 10" >&2
    exit 1
fi

total=0
for kind in $kinds; do
    requests=$output_dir/$kind.requests.ndjson
    "$probe" generate "$kind" > "$requests"
    count=$(wc -l < "$requests" | tr -d ' ')
    total=$((total + count))

    for engine_name in rust ocaml racket; do
        case $engine_name in
            rust) engine=$rust_engine ;;
            ocaml) engine=$ocaml_engine ;;
            racket) engine=$racket_engine ;;
        esac
        raw=$output_dir/$kind.$engine_name.raw
        canonical=$output_dir/$kind.$engine_name.canonical
        normalized=$output_dir/$kind.$engine_name.ndjson
        "$engine" < "$requests" > "$raw"
        response_count=$(wc -l < "$raw" | tr -d ' ')
        if [ "$response_count" -ne "$count" ]; then
            echo "$engine_name returned $response_count of $count responses for $kind" >&2
            exit 1
        fi
        "$probe" normalize < "$raw" > "$canonical"
        LC_ALL=C sort "$canonical" > "$normalized"
    done

    if ! cmp -s "$output_dir/$kind.rust.ndjson" "$output_dir/$kind.ocaml.ndjson"; then
        echo "census $kind differs between Rust and OCaml" >&2
        exit 1
    fi
    if ! cmp -s "$output_dir/$kind.rust.ndjson" "$output_dir/$kind.racket.ndjson"; then
        echo "census $kind differs between Rust and Racket" >&2
        exit 1
    fi
    if ! cmp -s "$output_dir/$kind.ocaml.ndjson" "$output_dir/$kind.racket.ndjson"; then
        echo "census $kind differs between OCaml and Racket" >&2
        exit 1
    fi

    # Backticks are literal Markdown, not shell substitutions.
    # shellcheck disable=SC2016
    printf '| `%s` | %s | 0 | 0 | 0 |\n' "$kind" "$count" >> "$rows"
    echo "census $kind: $count cases, zero differences"
done

if [ "$total" -lt 122199 ]; then
    echo "census generated $total cases; expected at least 122199" >&2
    exit 1
fi

{
    # REUSE-IgnoreStart
    # These are HTML comments emitted into the generated Markdown, not this script's license.
    echo '<!-- SPDX-FileCopyrightText: 2026 jlreq contributors -->'
    echo '<!-- SPDX-License-Identifier: MIT OR Apache-2.0 -->'
    # REUSE-IgnoreEnd
    echo '<!-- Generated by engines/census-all.sh; do not edit by hand. -->'
    echo '# Conformance census summary'
    echo
    # Backticks are literal Markdown, not shell substitutions.
    # shellcheck disable=SC2016
    echo 'Protocol `jlreq.conformance/1`, specification `jlreq-2020-08-11+unicode-17.0.0`.'
    echo
    echo '| Census | Cases | Rust ↔ OCaml | Rust ↔ Racket | OCaml ↔ Racket |'
    echo '| --- | ---: | ---: | ---: | ---: |'
    cat "$rows"
    printf '| **Total** | **%s** | **0** | **0** | **0** |\n' "$total"
} > "$generated_summary"

if ! cmp -s "$generated_summary" "$committed_summary"; then
    echo "$committed_summary is stale; replace it with $generated_summary" >&2
    exit 1
fi

echo "census-all: $kind_count kinds, $total cases, zero three-engine differences"
