# SPDX-FileCopyrightText: 2026 jlreq contributors
#
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "jlreq-fuzz"
version = "0.1.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "=0.4.13"
font-test-data = "=0.9.1"
jlreq = { path = "../crates/jlreq" }
jlreq-core = { path = "../crates/jlreq-core" }
serde_json = "1.0"

[[bin]]
name = "input_validation"
path = "fuzz_targets/input_validation.rs"
test = false
doc = false
bench = false

[[bin]]
name = "composition"
path = "fuzz_targets/composition.rs"
test = false
doc = false
bench = false

[[bin]]
name = "protocol_parser"
path = "fuzz_targets/protocol_parser.rs"
test = false
doc = false
bench = false

[[bin]]
name = "high_level_layout"
path = "fuzz_targets/high_level_layout.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
